# Generated by Django 4.1.1 on 2022-09-24 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='requisition_form',
            field=models.FileField(upload_to='requisition/%Y/%m/%d/'),
        ),
    ]
