# Generated by Django 4.1.1 on 2022-09-24 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_alter_contact_requisition_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='requisition_form',
            field=models.ImageField(upload_to='Reguisition/'),
        ),
    ]
