# Generated by Django 4.1.1 on 2022-09-10 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_Name', models.CharField(max_length=250)),
                ('designation', models.CharField(max_length=250)),
                ('Wing_Name', models.CharField(max_length=250)),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('mobile_No', models.PositiveIntegerField()),
                ('facebook_Link', models.URLField()),
                ('email_Address', models.EmailField(max_length=254)),
                ('created_Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
