# Generated by Django 4.1.1 on 2022-09-22 02:37

import ckeditor.fields
import datetime
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_No', models.CharField(max_length=255)),
                ('type_of_Vehicle', models.CharField(choices=[('Jeep', 'Jeep'), ('Pickup', 'Pickup'), ('Minibus', 'Minibus'), ('Truck', 'Truck'), ('Car', 'Car'), ('Micro', 'Micro'), ('Motor-Cycle', 'Motor-Cycle')], max_length=100)),
                ('origin', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('Brand_Name', models.CharField(max_length=100)),
                ('manufacture_Year', models.IntegerField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)], verbose_name='year')),
                ('engine_Displacement_CC', models.IntegerField()),
                ('car_photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('car_photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('car_photo_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('car_photo_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('car_photo_4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('features', multiselectfield.db.fields.MultiSelectField(choices=[('Air Conditioning', 'Air Conditioning'), ('Rear View Monitor', 'Rear View Monitor'), ('Audio Interface', 'Audio Interface'), ('Color LCD multi information display', 'Color LCD multi information display'), ('Non-Air Conditioning', 'Non-Air Conditioning'), ('USB port and Charging Outlets', 'USB port and Charging Outlets'), ('Alarm System', 'Alarm System'), ('ParkAssist', 'ParkAssist'), ('Power Steering', 'Power Steering'), ('Reversing Camera', 'Reversing Camera'), ('Direct Fuel Injection', 'Direct Fuel Injection'), ('Auto Start/Stop', 'Auto Start/Stop'), ('Wind Deflector', 'Wind Deflector'), ('Bluetooth Handset', 'Bluetooth Handset')], max_length=350)),
                ('transmission_Type', models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic')], max_length=100)),
                ('seating_Capacity', models.IntegerField()),
                ('engine_No', models.CharField(max_length=100)),
                ('chassis_No', models.CharField(max_length=100)),
                ('fuel_Type', models.CharField(choices=[('Diesel', 'Diesel'), ('Octane', 'Octane'), ('Petrol', 'Petrol'), ('CNG', 'CNG'), ('Others', 'Others')], max_length=10)),
                ('fuel_Tank_Capacity', models.IntegerField()),
                ('name_of_Owner', models.CharField(max_length=100)),
                ('passenger_Information', ckeditor.fields.RichTextField()),
                ('driver_Name', models.CharField(max_length=200)),
                ('blood_Group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-')], max_length=20)),
                ('driver_Photo', models.ImageField(upload_to='driver/%Y/%m/%d/')),
                ('driver_Mobile_No', models.IntegerField()),
                ('licence_No', models.CharField(max_length=150)),
                ('date_of_Birth', models.DateField(max_length=150)),
                ('is_requisition', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
